name: Core Automation Workflow

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
      source_repo:
        required: true
        type: string

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Echo source
        run: echo "Triggered from ${{ inputs.source_repo }} with release tag ${{ inputs.release_tag }}"

      # Add your automation logic here
